version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    allow:
      # Allow both direct and indirect updates for all packages
      - dependency-type: "all"
