name: Deploy Images to GHCR

on:
  push:
    branches:
      - main
    tags-ignore:
      - 'v*.*.*'

env:
  TAG: latest

jobs:
  push-image:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: 'Build and push Image'
        env:
          IMAGE_TAG: ${{ env.TAG }}
          GHCR_REPOSITORY: ${{ github.event.repository.name }}
          GHCR_USER: ${{ secrets.GHCR_USER }}
        run: |
          docker build -f .docker/Dockerfile --tag ghcr.io/$GHCR_USER/$GHCR_REPOSITORY:$IMAGE_TAG .
          docker push ghcr.io/$GHCR_USER/$GHCR_REPOSITORY:$IMAGE_TAG
