name: Build container

on:
  push:
    branches:
      - main
    tags-ignore:
      - 'v*.*.*'

permissions:
  contents: 'read'
  packages: 'write'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v4
        env:
          IMAGE_TAG: ${{ github.sha }}
          GHCR_REPOSITORY: ${{ github.event.repository.name }}
          GHCR_USER: ${{ secrets.GHCR_USER }}
        with:
          push: true
          tags: ghcr.io/$GHCR_USER/$GHCR_REPOSITORY:$IMAGE_TAG
          file: /.docker/Dockerfile
