name: Deploy to AZ App Service

on:
  workflow_run:
    workflows: ["Build container"]
    types:
      - completed

env:
  AZURE_WEBAPP_NAME: ${{ github.event.repository.name }}

jobs:

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}/docs
    env:
        ENVIRONMENT: staging
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        env:
          IMAGE_TAG: ${{ github.sha }}
          GHCR_REPOSITORY: ${{ github.event.repository.name }}
          GHCR_USER: ${{ secrets.GHCR_USER }}
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZ_PUBLISH_PROFILE }}
          images: 'ghcr.io/$GHCR_USER/$GHCR_REPOSITORY:$IMAGE_TAG'
